package com.freelancerk.type;

public enum DeadlineAlarmType {
    PROJECT_END_POSTING_AT, PROJECT_END_POSTING, CONTEST_END_POSTING_AT, CONTEST_END_POSTING,
    PROJECT_NEED_RATING, PICK_ME_UP_OPEN_END, PICK_ME_UP_OPTION_END
}
