package com.freelancerk.io;

public enum KpiOrdering {
    NO, NAME, NICKNAME, ACCESS, PROJECT, CONTEST, PROPOSITION, DIRECT, RATINGS, TRANSACTION_AMOUNT, COMPLETED,
    TOTAL_OPTION_COUNT, TOTAL_OPTION_AMOUNT, POINT
}
